[package]
name = "model-randgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
models = { path = "../" }
rand = "0.8"
rayon = "1"
serde_json = "1"
serde = "1"
